### ISSUE TITLE
Skin doesn't properly load when changing name.

### ISSUE THREAD

**Issue by AxeVillager** [Alvin-LB/NameTagChanger#6] opened 2018-06-25 16:29 UTC
After changing nametag, other players don't see the outer layer of the skin of the player until the skin loads for them again. This can be fixed by reconnecting to the server or walking away and coming back, making the Minecraft client load the skin again. However, I would rather this was not needed. After changing name, I would like the player's skin to update properly without having to do anything else.

The code I am using is as following. I am using `NameTagChanger`'s `changePlayername(player, newName)` method.

```
private void setNameTag(String name) {
    nameTagChanger.changePlayerName(player, name);
}
```

In the [JavaDocs](https://bringholm.com/javadocs/nametagchanger/com/bringholm/nametagchanger/NameTagChanger.html) I am told it is not necessary to update the player by the use of the `updatePlayer(player)` method since `changePlayerName(player, name)` does that automatically. Even so, the skin is not updating properly. 

I have tried to call the `updatePlayer(player)` method, to no avail. The skin still doesn't appear as it should.

The pictures below show this in action.

> Axe_Villager stand ready to change name.
>
> ![nametagchanger-issue-1-1](https://user-images.githubusercontent.com/21196871/41861816-968ee504-78a2-11e8-845c-9d06b743dea7.png)
> 
>
> 
> Axe_Villager changes name to "Name change". His skin now appears incomplete, the outer layer of the skin is not showing.
>
> ![nametagchanger-issue-1-2](https://user-images.githubusercontent.com/21196871/41861830-9dd5bb44-78a2-11e8-89e4-ea9b9ae0ed93.png)
> 
> 
>
> Axe_Villager reconnects to the server to force the other player's Minecraft client to load the skin. Now it appear as it should.
>
> ![nametagchanger-issue-1-4](https://user-images.githubusercontent.com/21196871/41861853-a645fd5c-78a2-11e8-9bab-8febab148a08.png)
> ![nametagchanger-issue-1-3](https://user-images.githubusercontent.com/21196871/41861861-a975284a-78a2-11e8-92b3-d741a7601f6b.png)
> 

Tested on: `Spigot 1.12.2`, `ProtocolLib  4.4.0-SNAPSHOT-b399` and `NameTagChanger v1.1-SNAPSHOT`.

**Comment by Alvin-LB** [comment] 2018-06-25 20:03
Thank you for the well-documented report!

I managed to fix the issue. Turns out I had forgotten to write the DataWatcher when manually respawning players after their names changed on the ProtocolLib implementation. Download the latest version of 1.1-SNAPSHOT or run the command `mvn clean -U install` if you are using maven, and you should be good to go.

**Comment by AxeVillager** [comment] 2018-06-25 22:07
Thank you so much, both for fixing the issue and responding so quickly! Truly marvelous!

**Comment by Alvin-LB** [comment] 2018-06-25 22:11
Glad I could be of help!

**Comment by AxeVillager** [comment] 2018-06-25 22:50
I apologize if this is not properly done. Because of little experience with GitHub I don't know if it is possible for you to open the issue now that you have closed it. I hesitate to create a new issue since I feel like the problem I encounter is very similar to what this issue is all about. Please excuse me if this is not handled correctly, I am willing to create a new issue if need be.

Even though the skin properly updates upon name change, the items the player is carrying and has equipped disappear when changing name. Identical to the original issue, the items appear invisible until the player is loaded anew by the Minecraft client.

> Axe_Villager has armour and weapons equipped before changing name.
> 
> ![nametagchanger-issue-armour-1](https://user-images.githubusercontent.com/21196871/41879525-51107258-78da-11e8-9867-e540aa7969e5.png)
> 
> The armour and weapons disappear upon name change. Axe_Villager does in fact still carry what he carried before, it is just not visible for the other player.
> 
> ![nametagchanger-issue-armour-2](https://user-images.githubusercontent.com/21196871/41879529-53f3db90-78da-11e8-84d8-0993d6227333.png)

Is it possible to make the items the player holds and carries reappear?

Tested on: `Spigot 1.12.2`, `ProtocolLib 4.4.0-SNAPSHOT-b399` and `NameTagChanger v1.1-SNAPSHOT` (updated version).

**Comment by Alvin-LB** [comment] 2018-06-26 07:18
Interesting. Like you say, the issue is quite similar to the previous one, so I think it might be a good idea to just reopen this issue (although I believe this issue is caused by something different in the code).

I'll see what I can do.

**Comment by Alvin-LB** [comment] 2018-06-26 09:12
Turns out there is a whole separate packet for entity equipment. I have now fixed it so it gets sent when manually respawning the players.

Redownload the latest version of `1.1-SNAPSHOT` and you should no longer have the issue.

**Comment by AxeVillager** [comment] 2018-06-26 12:46
Now the outer skin layer, weapons and armour update as it should. However, it introduced a new issue: When a player changes name while other players are online, the other players are kicked from the server.

In the server's console, no stacktrace is sent apart from a sign of null pointer exceptions `java.lang.NullPointerException`, two for each player kicked, without any other information.

> ![image](https://user-images.githubusercontent.com/21196871/41911939-5e467750-794e-11e8-8707-87175de8524b.png)

The picture below displays the exception in Minecraft a player receives upon being kicked when a player changes name.

> ![nametagchanger-issue-3-1](https://user-images.githubusercontent.com/21196871/41911011-b71ebc32-794b-11e8-83c9-f50ad7ce1aaa.png)

In case it is needed, here is that same `Internal Exception` in text form:

> ```
> Internal Exception: io.netty.handler.codec.DecoderException: 
> java.lang.IndexOutOfBoundsException: readerIndex(4) + length(2) exceeds 
> writerIndex(4): PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4)
> ```

I thought perhaps this was caused by something that wasn't related to the plugin, so I did some tests to investigate its behaviour:

- Create new/change Minecraft game directories
- Connect to different servers
- Log on different accounts from the same computer and on different computers
- Disable the plugin

For all the tests I ran, the issue stopped only when I disabled the plugin. Therefore I reason it is in fact the plugin `RolePlayName` that is using `NameTagChanger v1.1-SNAPSHOT` and `ProtocolLib 4.4.0-SNAPSHOT-b399` that causes the issue.

Is this fixable?

**Comment by Alvin-LB** [comment] 2018-06-26 12:51
Right, and this never happened before the most recent change that I made?

**Comment by AxeVillager** [comment] 2018-06-26 13:25
Correct, this never happened before the most recent change that you made.

**Comment by Alvin-LB** [comment] 2018-06-26 13:52
Turns out this is actually an issue with ProtocolLib. A method which [says it never returns null](https://github.com/dmulloy2/ProtocolLib/blob/master/modules/API/src/main/java/com/comphenix/protocol/utility/MinecraftReflection.java#L1929) returns null for ItemStacks with `Material.AIR` converted to CraftItemStacks.

I will report this in the ProtocolLib repository. In the mean time, I have pushed an update which will work around this error.

If there are no more problems, then we can *fingers crossed* close this issue.

**Comment by AxeVillager** [comment] 2018-06-26 14:14
Wonderful! The problem is fixed and I haven't encountered any other issues as of now. It seems you can possibly close this once and for all. Thank you!

**Comment by Alvin-LB** [comment] 2018-06-26 14:21
Great! I will now close this issue.

I have also [reported the ProtocolLib issue](https://github.com/dmulloy2/ProtocolLib/issues/483) in the ProtocolLib repo.

**Closed as completed by Alvin-LB** 2018-06-26 14:22 UTC
